### ISSUE TITLE
Error running DaemonApi

### ISSUE THREAD

**Issue by pablanco** [oipwg/js-oip#9]
Hey, I am running sample code to start implement something with FLO

```
const DaemonApi = require('js-oip');

let api = new DaemonApi();
const limit = 50;
async function asyncExample() {

    let {success, artifacts, error} = await api.getLatestArtifacts(limit);
    console.log(success);
    console.log(error);
    console.log(artifacts);
}

asyncExample();
```

I am getting this error:

```
/node_modules/pull-stream-to-async-iterator/index.js:4
  return (async function * () {
                         ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/.../node_modules/async-iterator-to-pull-stream/index.js:2:20)
```

```
npm -v
5.5.1
node -v
v8.9.0
```

Do you have any issue with these npm/node versions or am I doing something wrong?

**Comment by pablanco** [comment]
I have tried to update my node version to

```
node -v
v10.13.0
npm -v
6.4.1
```

But now I am getting this:

```
internal/modules/cjs/loader.js:582
    throw err;
    ^
Error: Cannot find module 'core-js/modules/es6.regexp.to-string'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/pblanco/Proyectos/oip-flo/node_modules/js-oip/lib/core/oip/oip.js:8:1)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
```

**Comment by mcfang** [comment]
install core-js@^2.6.5 to your project can fix the problem.

**Comment by pablanco** [comment]
Cool, that fixed the problem. Thanks!
